import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Academy of English',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className="bg-[#E0F7FE]" >
                {children}
            </body>
        </html >
    )
}